copyright: >
  Copyright &copy; 2023 Mac Lawson –
  <a href="#__consent">Change cookie settings</a>


site_name: Tensorgo Documentation
theme:
  name: material
  icon:
    logo: fontawesome/brands/golang
  features:
    - navigation.instant
    - navigation.tabs
    - announce.dismiss

nav:
  - Introduction: 'index.md'
  - Cloud Server: 'cloudserver.md'
  - Tensor: 'tensor.md'

  - 'Go Documentation': 'https://go.dev/'

plugins:
  - search

extra:
  generator: false
  consent:
    title: Cookie consent
    description: >- 
      Tensorgo uses cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.
    actions:
      - accept
      - reject



